### pip install pandas

- different methods to create dataset
- reading dataset from external sources
- basic insights of dataset
- selection of data         
    - row wise selection
    - columns wise selection
- Data Cleaning and manipulaiton

In [159]:
import pandas as pd

In [160]:
movies = {
    'tital' : ["PK", 'DDLJ','T','RRR'],
    'year' : [2014, 1976, 9872,3673],
    'rating' : [4.6, 5.4, 6.5, 5.4]
}
df = pd.DataFrame(movies)
df

  tital  year  rating
0    PK  2014     4.6
1  DDLJ  1976     5.4
2     T  9872     6.5
3   RRR  3673     5.4

In [161]:
#to save the above dataframe to a csv file
df.to_csv('movies.csv',index=True)

In [162]:
df

  tital  year  rating
0    PK  2014     4.6
1  DDLJ  1976     5.4
2     T  9872     6.5
3   RRR  3673     5.4

# new
    2 type of path
# absulute path

In [163]:
# absulute path

df = pd.read_csv(r"C:\Users\Hp\Desktop\python clss\Data Analytics\kc_house_data.csv")

In [164]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

# Relative Path

In [165]:
df = pd.read_csv("kc_house_data.csv")

In [166]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

# csv file me data check krne wala basic commond

In [167]:
df.head() #first 5 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [168]:
df.head(2) # first ke 2 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639

In [169]:
df.tail() #lsst 5 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [170]:
df.tail(2) #last ke 2 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [171]:
df.sample() #random koi bhi row de dega

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
4048,1105000745,20150123T000000,227064.0,3,1.5,1570,10824,2.0,0,0,...,7,1570,0,1908,0,98118,47.54,-122.275,1530,8125

In [172]:
df.sample(5) # 5 koi random row de dega

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
6898,4327600010,20150202T000000,336000.0,3,3.00,1790,13350,1.0,0,0,...,7,1190,600,1988,0,98178,47.4958,-122.262,1740,10624
9456,3623059101,20140811T000000,420000.0,3,3.00,2700,47050,2.0,0,0,...,9,1570,1130,1986,0,98058,47.4446,-122.104,2260,45901
15935,6055000010,20140725T000000,470000.0,3,3.50,3520,35512,2.0,0,2,...,8,2760,760,2005,0,98022,47.2416,-121.979,2860,39614
9021,7010700110,20140916T000000,440000.0,3,2.25,1760,1800,2.0,0,0,...,7,1330,430,1983,0,98199,47.6579,-122.394,1150,4575
20737,4046500160,20140729T000000,441000.0,3,2.00,1720,15000,1.0,0,0,...,9,1720,0,2011,0,98014,47.6927,-121.920,1900,15337

In [173]:
df.info() #to get the information about dataframe in concise ,amm

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [174]:
df.describe() # numeric data ka mean, median, min, max ek baar me dekhne ke liye

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.401822e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.673622e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [175]:
df.columns #to get the coloumn names of the dataframe

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [176]:
df.columns.tolist() #to get the column names of the dataframe in list

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [177]:
df.iloc[7587]  # esme hm koi bhi specific data ko hm nekal skte hai koi ek hi data ayega

id                    4104910040
date             20140701T000000
price                   548000.0
bedrooms                       4
bathrooms                    2.5
sqft_living                 2440
sqft_lot                   11005
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          9
sqft_above                  2440
sqft_basement                  0
yr_built                    1994
yr_renovated                   0
zipcode                    98056
lat                      47.5318
long                    -122.176
sqft_living15               2590
sqft_lot15                 14754
Name: 7587, dtype: object

In [178]:
df.iloc[7265:7269] # koi bhi specific data ko hm neekal skte hai us frame se jo dil kre jaha se jaha tak

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7265,123039642,20150501T000000,540000.0,3,2.50,1970,14876,1.0,0,0,...,7,1320,650,1981,0,98146,47.5031,-122.372,2030,8008
7266,8718500095,20150507T000000,415000.0,3,1.50,1740,9046,1.0,0,0,...,7,1740,0,1956,0,98028,47.7402,-122.255,1830,9513
7267,1774000780,20150105T000000,469500.0,4,2.75,1930,13041,1.0,0,0,...,8,1180,750,1980,0,98072,47.7502,-122.085,1880,10234
7268,2421039075,20141106T000000,195000.0,3,1.75,1190,14777,1.0,0,0,...,7,1190,0,1965,0,98023,47.2933,-122.377,2240,8325

In [179]:
df.shape  # Yeh batayega kitne (rows, columns) hain

(21613, 21)

In [180]:
df.isnull().sum()  # Har column me kitne khaali cells hain batayega

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [181]:
df.dropna()  # Khaali rows ko delete karne ke liye
df.fillna(0)  # Khaali jagah par 0 ya koi value bharne ke liye

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [182]:
#(inplace=True) Matlab: Jo bhi badlav (change) hum kar rahe hain, use original DataFrame (table) ke andar hi permanent apply kar do
#Ek hi entry agar baar-baar ho toh use saaf karne ke liye
#Kahan use hota hai: df.drop(), df.fillna(), df.dropna(), df.rename() ke saath

df.drop_duplicates(inplace=True)

In [183]:
# df.rename(columns={'purana_naam': 'naya_naam'}, inplace=True) #Galt ya ajeeb columns ke naam sahi karne ke liye

# df.rename(columns={'bathroom': 'bathrooms'}, inplace=True)

In [184]:
# df.groupby('Department')['Salary'].mean()  #Category ke hisab se average ya total nikalna (jaise har Department ki average salary)

df.groupby('price')['grade'].mean()

price
75000.0       3.0
78000.0       5.0
80000.0       4.0
81000.0       5.0
82000.0       6.0
             ...
5350000.0    12.0
5570000.0    13.0
6890000.0    13.0
7060000.0    11.0
7700000.0    13.0
Name: grade, Length: 3625, dtype: float64

In [185]:
# Kisi column me kaun si value kitni baar aayi hai (jaise kis city ke kitne customers hain)     
# df['Column_Name'].value_counts()

df['price'].value_counts()

price
450000.0     172
350000.0     172
550000.0     159
500000.0     152
425000.0     150
            ...
3570000.0      1
594866.0       1
541800.0       1
610685.0       1
402101.0       1
Name: count, Length: 3625, dtype: int64

In [186]:
# ascending=False   Data ko "Bade se Chote ki tarf lane me ya highest Salary sabse upar  ya Z se A
# Highest salary,price,room,bathrooms, upar aayega jo digits me sabse jyda hoga  
df.sort_values(by='price', ascending=False)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
7252,6762700020,20141013T000000,7700000.0,6,8.00,12050,27600,2.5,0,3,...,13,8570,3480,1910,1987,98102,47.6298,-122.323,3940,8800
3914,9808700762,20140611T000000,7060000.0,5,4.50,10040,37325,2.0,1,2,...,11,7680,2360,1940,2001,98004,47.6500,-122.214,3930,25449
9254,9208900037,20140919T000000,6890000.0,6,7.75,9890,31374,2.0,0,4,...,13,8860,1030,2001,0,98039,47.6305,-122.240,4540,42730
4411,2470100110,20140804T000000,5570000.0,5,5.75,9200,35069,2.0,0,0,...,13,6200,3000,2001,0,98039,47.6289,-122.233,3560,24345
1448,8907500070,20150413T000000,5350000.0,5,5.00,8000,23985,2.0,0,4,...,12,6720,1280,2009,0,98004,47.6232,-122.220,4600,21750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8274,3883800011,20141105T000000,82000.0,3,1.00,860,10426,1.0,0,0,...,6,860,0,1954,0,98146,47.4987,-122.341,1140,11250
16198,3028200080,20150324T000000,81000.0,2,1.00,730,9975,1.0,0,0,...,5,730,0,1943,0,98168,47.4808,-122.315,860,9000
465,8658300340,20140523T000000,80000.0,1,0.75,430,5050,1.0,0,0,...,4,430,0,1912,0,98014,47.6499,-121.909,1200,7500
15293,40000362,20140506T000000,78000.0,2,1.00,780,16344,1.0,0,0,...,5,780,0,1942,0,98168,47.4739,-122.280,1700,10387
1149,3421079032,20150217T000000,75000.0,1,0.00,670,43377,1.0,0,0,...,3,670,0,1966,0,98022,47.2638,-121.906,1160,42882

- row wise selection
    - iloc : index base selection 
    - loc : label base selection
- coloumn wise selection
    - single column selection
        - dictionary like selection
        - object like selection
    - multiple coloumn selection
        - dictionary like selection

In [187]:
df.iloc[2]
df.iloc[-2]

id                     291310100
date             20150116T000000
price                   400000.0
bedrooms                       3
bathrooms                    2.5
sqft_living                 1600
sqft_lot                    2388
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          8
sqft_above                  1600
sqft_basement                  0
yr_built                    2004
yr_renovated                   0
zipcode                    98027
lat                      47.5345
long                    -122.069
sqft_living15               1410
sqft_lot15                  1287
Name: 21611, dtype: object

In [188]:
df.iloc[1:5] # hme 1 se 5 taik sabhi mil jyega data hme jo bhi cahiye ham waha wo digit liikh skte hai

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [189]:
df.iloc[1:12:2]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1230000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000

In [190]:
df.iloc[2] #to get the 3rd row of the dataframe

id                    5631500400
date             20150225T000000
price                   180000.0
bedrooms                       2
bathrooms                    1.0
sqft_living                  770
sqft_lot                   10000
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                          6
sqft_above                   770
sqft_basement                  0
yr_built                    1933
yr_renovated                   0
zipcode                    98028
lat                      47.7379
long                    -122.233
sqft_living15               2720
sqft_lot15                  8062
Name: 2, dtype: object

In [191]:
df.iloc[[3,4,5,7,8,23,54]]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1230000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
23,8091400200,20140516T000000,252700.0,2,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
54,4217401195,20150303T000000,920000.0,5,2.25,2730,6000,1.5,0,0,...,8,2130,600,1927,0,98105,47.6571,-122.281,2730,6000

In [192]:
df = df.set_index('id') #to set the index of the dataframe to the 'id' column
df
# 2nd method
# df.set_index('id', inplace=True) #to set the index of the dataframe to the 'id' column
# df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [193]:
df.loc[1523300141]

date             20140623T000000
price                   402101.0
bedrooms                       2
bathrooms                   0.75
sqft_living                 1020
sqft_lot                    1350
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  1020
sqft_basement                  0
yr_built                    2009
yr_renovated                   0
zipcode                    98144
lat                      47.5944
long                    -122.299
sqft_living15               1020
sqft_lot15                  2007
Name: 1523300141, dtype: object

In [194]:
df.loc[7129300520:1954400510] #end range is inclusive

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [195]:
df.loc[[2487200875,2414600126]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
2487200875,20141209T000000,604000.0,4,3.0,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
2414600126,20150415T000000,229500.0,3,1.0,1780,7470,1.0,0,0,3,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113

#### DATA  CLEANING AND MANIPULATION
- Dropping row and coloumn 
- renaming rows and column
- changing datatype of a column
- deleting missing values
- handling missing values
- replacing values
- check duplicate row
- delete duplicate row
- find out uniqie values in a column
- find out number of unique values in a columns
- value frequency count
- value sorting

In [196]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [197]:
df = df.drop(columns=['sqft_living15'])
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_lot15'],
      dtype='str')

In [198]:
df.head

<bound method NDFrame.head of                        date     price  bedrooms  bathrooms  sqft_living  \
id
7129300520  20141013T000000  221900.0         3       1.00         1180
6414100192  20141209T000000  538000.0         3       2.25         2570
5631500400  20150225T000000  180000.0         2       1.00          770
2487200875  20141209T000000  604000.0         4       3.00         1960
1954400510  20150218T000000  510000.0         3       2.00         1680
...                     ...       ...       ...        ...          ...
263000018   20140521T000000  360000.0         3       2.50         1530
6600060120  20150223T000000  400000.0         4       2.50         2310
1523300141  20140623T000000  402101.0         2       0.75         1020
291310100   20150116T000000  400000.0         3       2.50         1600
1523300157  20141015T000000  325000.0         2       0.75         1020

            sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
id
7129300520      5650     1.0           0     0          3      7        1180
6414100192      7242     2.0           0     0          3      7        2170
5631500400     10000     1.0           0     0          3      6         770
2487200875      5000     1.0           0     0          5      7        1050
1954400510      8080     1.0           0     0          3      8        1680
...              ...     ...         ...   ...        ...    ...         ...
263000018       1131     3.0           0     0          3      8        1530
6600060120      5813     2.0           0     0          3      8        2310
1523300141      1350     2.0           0     0          3      7        1020
291310100       2388     2.0           0     0          3      8        1600
1523300157      1076     2.0           0     0          3      7        1020

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
id
7129300520              0      1955             0    98178  47.5112 -122.257
6414100192            400      1951          1991    98125  47.7210 -122.319
5631500400              0      1933             0    98028  47.7379 -122.233
2487200875            910      1965             0    98136  47.5208 -122.393
1954400510              0      1987             0    98074  47.6168 -122.045
...                   ...       ...           ...      ...      ...      ...
263000018               0      2009             0    98103  47.6993 -122.346
6600060120              0      2014             0    98146  47.5107 -122.362
1523300141              0      2009             0    98144  47.5944 -122.299
291310100               0      2004             0    98027  47.5345 -122.069
1523300157              0      2008             0    98144  47.5941 -122.299

            sqft_lot15
id
7129300520        5650
6414100192        7639
5631500400        8062
2487200875        5000
1954400510        7503
...                ...
263000018         1509
6600060120        7200
1523300141        2007
291310100         1287
1523300157        1357

[21613 rows x 19 columns]>

In [199]:
# renaming columns in te dataframe
renamed_cols = {
    'lat' : 'lattitude',
    'long' : 'longitude',
}
df = df.rename(columns=renamed_cols)
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lattitude',
       'longitude', 'sqft_lot15'],
      dtype='str')

In [200]:

cols = list(df.columns)
cols[0] = 'ID'
df.columns = cols

In [201]:
df.columns

Index(['ID', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lattitude',
       'longitude', 'sqft_lot15'],
      dtype='str')

In [202]:
df.info()

<class 'pandas.DataFrame'>
Index: 21613 entries, 7129300520 to 1523300157
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21613 non-null  str
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  int64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  int64
 16  lattitude      21613 non-null  float64
 17  longitude      21613 non-null  float64
 18  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(13), str(1)
memory usage: 3.8 MB

In [203]:
# changing datatype
df = df.astype({'bedrooms': 'float64'})
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 21613 entries, 7129300520 to 1523300157
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21613 non-null  str
 1   price          21613 non-null  float64
 2   bedrooms       21613 non-null  float64
 3   bathrooms      21613 non-null  float64
 4   sqft_living    21613 non-null  int64
 5   sqft_lot       21613 non-null  int64
 6   floors         21613 non-null  float64
 7   waterfront     21613 non-null  int64
 8   view           21613 non-null  int64
 9   condition      21613 non-null  int64
 10  grade          21613 non-null  int64
 11  sqft_above     21613 non-null  int64
 12  sqft_basement  21613 non-null  int64
 13  yr_built       21613 non-null  int64
 14  yr_renovated   21613 non-null  int64
 15  zipcode        21613 non-null  int64
 16  lattitude      21613 non-null  float64
 17  longitude      21613 non-null  float64
 18  sqft_lot15     21613 non-null  int64
dtypes: float64(6), int64(12), str(1)
memory usage: 3.8 MB

,ID,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lattitude,longitude,sqft_lot15
id,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3.0,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,5650
6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,7639
5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,8062
2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,5000
1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,7503

In [204]:
import seaborn as sns
sns.get_dataset_names() #gives the list of avaible datasets in seabord

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [205]:
titanic = sns.load_dataset('titanic') #load the titanic dataset frome sebaborn
titanic.isnull().sum() #gives the count of null values in each column of the titanic dataset

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

- When a column has <40% missing values of the data, then we simply remove that column
- When a column has <40% missing values of data, then we handle those missing values means we replace those missing values with any number
    - here are two type of colums in any dataset - CATAGORICAL & NUMARICAL
    - When the column is numarical, we always replace the null values with the column mean(average)
    - When the column is categorical, we always replace the null values with mostfrequent(mode) values

In [206]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [207]:
titanic = titanic.dropna(subset=['embarked']) #drop the rows where the embarked column has nulll values
titanic.isnull().sum() #gives the count of null values in each column

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [208]:
avg_age = round(titanic['age'].mean()) # calculate the average age of passengers in the titanic dataset
print(avg_age)

30

In [209]:
#replace null values with avg_age
titanic['age'] = titanic['age'].fillna(avg_age) #replace null values in the 'age column with avg_age
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [210]:
# checking duplicate values
titanic.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 889, dtype: bool

In [211]:
titanic.drop_duplicates()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [212]:
titanic["age"].unique()  #esse hm uniqe value dekh skte hai "age" ki jagh koi hi colloumn name de skte hai

array([22.  , 38.  , 26.  , 35.  , 30.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [213]:
# frequence  of values in a column
titanic['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [214]:
df.sort_index()

,ID,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lattitude,longitude,sqft_lot15
id,,,,,,,,,,,,,,,,,,,
1000102,20150422T000000,300000.0,6.0,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,7316
1000102,20140916T000000,280000.0,6.0,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,7316
1200019,20140508T000000,647500.0,4.0,1.75,2060,26036,1.0,0,0,4,8,1160,900,1947,0,98166,47.4444,-122.351,21891
1200021,20140811T000000,400000.0,3.0,1.00,1460,43000,1.0,0,0,3,7,1460,0,1952,0,98166,47.4434,-122.347,20023
2800031,20150401T000000,235000.0,3.0,1.00,1430,7599,1.5,0,0,4,6,1010,420,1930,0,98168,47.4783,-122.265,10320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9842300095,20140725T000000,365000.0,5.0,2.00,1600,4168,1.5,0,0,3,7,1600,0,1927,0,98126,47.5297,-122.381,4168
9842300485,20150311T000000,380000.0,2.0,1.00,1040,7372,1.0,0,0,5,7,840,200,1939,0,98126,47.5285,-122.378,5150
9842300540,20140624T000000,339000.0,3.0,1.00,1100,4128,1.0,0,0,4,7,720,380,1942,0,98126,47.5296,-122.379,4538
9895000040,20140703T000000,399900.0,2.0,1.75,1410,1005,1.5,0,0,3,9,900,510,2011,0,98027,47.5446,-122.018,1188
9900000190,20141030T000000,268950.0,3.0,1.00,1320,8100,1.0,0,0,3,6,880,440,1943,0,98166,47.4697,-122.351,8100

### DATA MANIPULATION

In [215]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [216]:
#adding a new column
titanic = titanic.assign(Discount=titanic["fare"]*0.10)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [217]:
titanic['fare'] = titanic['fare'].apply(lambda x:x*1.05)  # hm kahi bhi new column add kr skte hai
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [218]:
titanic["embarked"] = titanic["embarked"].map({
    "S" : "Southampton",
    "C" : "Cherbourg",
    "Q" : "Queentown",
})
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Queentown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [219]:
titanic.groupby("embarked")["fare"].mean()

embarked
Cherbourg      62.951851
Queentown      13.939831
Southampton    28.433802
Name: fare, dtype: float64

In [220]:
titanic.groupby("embarked")["fare"].max()

embarked
Cherbourg      537.94566
Queentown       94.50000
Southampton    276.15000
Name: fare, dtype: float64

In [221]:
titanic.groupby("sex")["fare"].min()

sex
female    7.0875
male      0.0000
Name: fare, dtype: float64

In [222]:
titanic.groupby("sex")["fare"].max()

sex
female    537.94566
male      537.94566
Name: fare, dtype: float64

In [223]:
#data feltring
titanic[titanic["survived"] == 1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.586250,Cherbourg,Third,child,False,NaN,Cherbourg,yes,True,0.72250
879,1,1,female,56.0,0,1,87.316215,Cherbourg,First,woman,False,C,Cherbourg,yes,False,8.31583
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000

In [224]:
#data feltring
titanic[titanic["sex"] == "female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
882,0,3,female,22.0,0,0,11.042535,Southampton,Third,woman,False,NaN,Southampton,no,True,1.05167
885,0,3,female,39.0,0,5,30.581250,Queentown,Third,woman,False,NaN,Queenstown,no,False,2.91250
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500

In [225]:
#sorting values
titanic.sort_values('fare',ascending=False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
679,1,1,male,36.0,0,1,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,False,51.23292
258,1,1,female,35.0,0,0,537.94566,Cherbourg,First,woman,False,NaN,Cherbourg,yes,True,51.23292
737,1,1,male,35.0,0,0,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,True,51.23292
341,1,1,female,24.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
88,1,1,female,23.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,0,3,male,36.0,0,0,0.00000,Southampton,Third,man,True,NaN,Southampton,no,True,0.00000
263,0,1,male,40.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
277,0,2,male,30.0,0,0,0.00000,Southampton,Second,man,True,NaN,Southampton,no,True,0.00000
815,0,1,male,30.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
822,0,1,male,38.0,0,0,0.00000,Southampton,First,man,True,NaN,Southampton,no,True,0.00000